# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/python_ds_utils',
                'doc_host': 'https://WittmannF.github.io',
                'git_url': 'https://github.com/WittmannF/python_ds_utils',
                'lib_path': 'ds_utils'},
  'syms': { 'ds_utils.core': { 'ds_utils.core.foo': ('core.html#foo', 'ds_utils/core.py'),
                               'ds_utils.core.say_hello': ('core.html#say_hello', 'ds_utils/core.py')}}}
