# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/python_ds_utils',
                'doc_host': 'https://WittmannF.github.io',
                'git_url': 'https://github.com/WittmannF/python_ds_utils',
                'lib_path': 'python_ds_utils'},
  'syms': {'python_ds_utils.core': {'python_ds_utils.core.foo': ('core.html#foo', 'python_ds_utils/core.py')}}}
